### ISSUE TITLE
No support for Linux arm64/aarch64

### ISSUE THREAD

**Issue by xuancong84** [pavlobu/deskreen#249]
It will be nice to have support on Linux arm64/aarch64, e.g., Raspberry Pi.

**Comment by gmicroul** [comment]
sudo yarn install
yarn install v1.22.19
$ node ./internals/scripts/CheckYarn.js
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > connected-react-router@6.8.0" has unmet peer dependency "immutable@^3.8.1 || ^4.0.0-rc.1".
warning " > connected-react-router@6.8.0" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
warning " > connected-react-router@6.8.0" has unmet peer dependency "seamless-immutable@^7.1.3".
warning " > browserslist-config-erb@0.0.1" has incorrect peer dependency "electron@^7.0.0".
warning " > eslint-config-airbnb@18.2.1" has incorrect peer dependency "eslint-plugin-jsx-a11y@^6.4.1".
warning " > eslint-config-erb@1.0.0" has incorrect peer dependency "eslint-config-airbnb-typescript@^8.0.2".
warning " > eslint-config-erb@1.0.0" has unmet peer dependency "eslint-plugin-flowtype@^5.1.3".
warning " > eslint-config-erb@1.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@6.2.3".
[4/4] Building fresh packages...
$ node -r @babel/register internals/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn build-dll && opencollective-postinstall
  • electron-builder  version=23.0.3
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=linux arch=arm64 appDir=/home/user/deskreen/app
yarn run v1.22.19
$ cross-env NODE_ENV=development webpack --config ./configs/webpack.config.renderer.dev.dll.babel.js --colors
node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/user/deskreen/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/user/deskreen/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/user/deskreen/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/user/deskreen/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/user/deskreen/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/user/deskreen/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/user/deskreen/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/user/deskreen/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/user/deskreen/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/user/deskreen/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/user/deskreen/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v21.4.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by meaw-lab** [comment]
Yes, please add support for aarch64 for Asahi Linux users

**Comment by antoinegomez** [comment]
You can fix with:

`export NODE_OPTIONS=--openssl-legacy-provider`
